.\" ***** BEGIN LICENSE BLOCK *****
.\" Copyright (C) 2009 Zmanda Incorporated. All Rights Reserved.
.\"
.\" This file is part of libzcloud.
.\"
.\" libzcloud is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU Lesser General Public License (the LGPL)
.\" as published by the Free Software Foundation, either version 2.1 of
.\" the LGPL, or (at your option) any later version.
.\"
.\" libzcloud is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"  ***** END LICENSE BLOCK *****

.TH zcloud 1 "2009-05-19" "LIBZCLOUD"
.SH NAME
zcloud - Command-line interface to libzcloud
.SH SYNOPSIS
\fBzcloud\fR \fBoperation\fR \fBstore-spec\fR \fB[key]\fR
.SH DESCRIPTION
\fBzcloud\fR provides command-line access to storage clouds via libzcloud.
.PP
At the moment, the entirety of its operation is to load a plugin based on
the given prefix and try to instantiate a \fIStore\fR.
.SS OPTIONS
.IP "--plugin-path \fBpath\fR"
You can use this to set the path that libzcloud will search for plugins.
Overrides ZCPLUGINPATH.
.IP "--param \fBname\fR=\fBvalue\fR"
Set parameter \fBname\fR to \fBvalue\fR.
.IP "--null"
(\fBlist\fR only) Print a NUL after each key.
.SS OPERATIONS
.IP "create"
Create \fBkey\fR in the store.
.IP "exists"
Test to see if \fBkey\fR exists in the store.
.IP "delete"
Delete \fBkey\fR from the store.
.IP "list"
List all keys in the store. If \fBkey\fR is supplied, it's used as a template
and only keys matching it are printed.
.SS EXIT STATUS
For most operations, \fBzcloud\fR returns 0 if the operation was successful and
1 if it was not. For the \fBexists\fR operation, 0 is returned if \fBkey\fR
exists and 2 is returned if it does not; 1 indicates an error, as usual.
.SS ENVIRONMENT VARIABLES
.IP "ZCPLUGINPATH"
The path that libzcloud will search for plugins.
.SH SEE ALSO
http://zmanda.github.com/libzcloud
.SH AUTHORS
This manual page was written by Dustin J. Mitchell <dustin@zmanda.com> and
Nikolas Coukouma <atrus@zmanda.com>.
