.\" ***** BEGIN LICENSE BLOCK *****
.\" Copyright (C) 2009 Zmanda Incorporated. All Rights Reserved.
.\"
.\" This file is part of libzcloud.
.\"
.\" libzcloud is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU Lesser General Public License (the LGPL)
.\" as published by the Free Software Foundation, either version 2.1 of
.\" the LGPL, or (at your option) any later version.
.\"
.\" libzcloud is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\"  ***** END LICENSE BLOCK *****

.TH zcloud 1 "2009-05-19" "LIBZCLOUD"
.SH NAME
zcloud - Command-line interface to libzcloud
.SH SYNOPSIS
\fBzcloud\fR \fBprefix\fR
.SH DESCRIPTION
\fBzcloud\fR provides command-line access to storage clouds via libzcloud.
.PP
At the moment, the entirety of its operation is to load a plugin based on
the given prefix and try to instantiate a \fIStore\fR.
.\" .SS OPTIONS
.\" .IP "-o, --option"
.\" What the option does
.SH SEE ALSO
(add link to Sphinx documentation here)
.SH AUTHORS
This manual page was written by Dustin J. Mitchell <dustin@zmanda.com> and Nikolas
Coukouma <atrus@zmanda.com>.
